# Copyright 2024 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: setup-krel
author: Vyom-Yadav
description: 'Installs krel and includes it in your path'
branding:
  icon: 'package'
  color: 'blue'

outputs:
  krel-path:
    description: 'Path to the installed krel binary'
    value: ${{ steps.install-krel.outputs.krel-path }}

runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5.1.0
      with:
        go-version: '1.23'
        check-latest: true

    - id: install-krel
      shell: bash
      run: |
        #!/usr/bin/env bash
        set -euo pipefail

        echo "Installing krel..."
        if ! go install k8s.io/release/cmd/krel@latest; then
          echo "::error::Failed to install krel"
          exit 1
        fi

        echo "Verifying krel installation..."
        if ! command -v krel &> /dev/null; then
          echo "::error::krel not found in PATH after installation"
          exit 1
        fi

        echo "Testing krel..."
        if ! krel --help &> /dev/null; then
          echo "::error::krel --help failed, installation may be corrupted"
          exit 1
        fi

        echo "krel installed successfully"
        KREL_PATH=$(which krel)
        echo "krel-path=$KREL_PATH" >> "$GITHUB_OUTPUT"
        echo "Krel path: $KREL_PATH"